# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relocate_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
